export const MACROSCOPY_TEMPLATES = {
    'Vesícula Biliar': {
        sampleType: 'Vesícula biliar',
        fragmentCount: '1',
        dimensions: '8 x 4 x 3 cm',
        color: 'Verdoso',
        consistency: 'Elástica',
        margins: 'No aplica',
        orientation: 'No orientada',
        findings: 'Serosa lisa y brillante. Al corte, pared de 0.3 cm de espesor. Mucosa aterciopelada teñida de bilis.',
        lesions: 'No se identifican cálculos ni lesiones focales.',
        observations: 'Se incluye corte representativo de fondo, cuerpo y cuello en 1 cápsula.'
    },
    'Apéndice Cecal': {
        sampleType: 'Apéndice cecal',
        fragmentCount: '1',
        dimensions: '6 x 0.8 cm',
        color: 'Pardo claro con áreas congestivas',
        consistency: 'Firme',
        margins: 'Base apendicular',
        orientation: 'No orientada',
        findings: 'Serosa deslustrada con fibrina adherida. Al corte, luz ocupada por material fecaloide.',
        lesions: 'No se identifican perforaciones.',
        observations: 'Se incluye punta y cortes seriados representativos en 2 cápsulas.'
    },
    'Biopsia de Piel (Losange)': {
        sampleType: 'Losange de piel',
        fragmentCount: '1',
        dimensions: '2.5 x 1.0 x 0.5 cm',
        color: 'Pardo claro',
        consistency: 'Elástica',
        margins: 'Bordes laterales y profundo',
        orientation: 'Hilo corto (hora 12), Hilo largo (hora 6)',
        findings: 'Epidermis con lesión central pigmentada de 0.6 cm, bordes irregulares.',
        lesions: 'Lesión pigmentada plana, no ulcerada.',
        observations: 'Se pintan márgenes con tinta china. Se incluye totalmente con cortes seriados en 3 cápsulas.'
    },
    'Biopsia de Piel (Punch)': {
        sampleType: 'Punch de piel',
        fragmentCount: '1',
        dimensions: '0.4 cm de diámetro',
        color: 'Blanquecino',
        consistency: 'Firme',
        margins: 'Periférico y profundo',
        orientation: 'No orientada',
        findings: 'Pequeño cilindro de tejido cutáneo con superficie epidérmica lisa.',
        lesions: 'No se identifican lesiones macroscópicas evidentes.',
        observations: 'Se incluye en su totalidad en 1 cápsula.'
    },
    'Mama (Mastectomía)': {
        sampleType: 'Producto de mastectomía radical',
        fragmentCount: '1',
        dimensions: '22 x 18 x 6 cm',
        color: 'Amarillento (tejido adiposo)',
        consistency: 'Blanda con áreas firmes',
        margins: 'Anterior, posterior, superior, inferior, medial y lateral',
        orientation: 'Cola de Spence identificada',
        findings: 'Piel de 15 x 10 cm con complejo pezón-areola. Al corte, parénquima sustituido mayormente por tejido graso.',
        lesions: 'En cuadrante superior externo se identifica masa firme, blanquecina, de bordes estrellados de 3.5 cm.',
        observations: 'Se identifican 15 ganglios en el rodete axilar. Se incluyen cortes de tumor, márgenes, cuadrantes y ganglios.'
    },
    'Próstata (Prostatectomía)': {
        sampleType: 'Próstata radical',
        fragmentCount: '1',
        dimensions: '5 x 4 x 3.5 cm',
        color: 'Pardo grisáceo',
        consistency: 'Firme elástica',
        margins: 'Uretral proximal, distal y radial',
        orientation: 'Derecha/Izquierda, Base/Ápice',
        findings: 'Cápsula íntegra, lisa. Al corte, parénquima con nódulos blanquecinos bilaterales.',
        lesions: 'Área de mayor firmeza en lóbulo derecho posterior de 1.2 cm.',
        observations: 'Se incluye la totalidad del órgano siguiendo protocolo de Stanford modificado.'
    },
    'Tiroides (Tiroidectomía)': {
        sampleType: 'Glándula tiroides (Tiroidectomía total)',
        fragmentCount: '1',
        dimensions: '6 x 4 x 2 cm',
        color: 'Pardo rojizo',
        consistency: 'Firme',
        margins: 'Cápsula tiroidea',
        orientation: 'Lóbulo derecho, lóbulo izquierdo e istmo',
        findings: 'Superficie externa multinodular. Al corte, parénquima con nódulos de contenido coloide.',
        lesions: 'Nódulo dominante en lóbulo derecho de 2.5 cm, bien delimitado, con áreas de hemorragia.',
        observations: 'Se incluyen cortes representativos de ambos lóbulos e istmo.'
    },
    'Estómago (Gastrectomía)': {
        sampleType: 'Gastrectomía subtotal',
        fragmentCount: '1',
        dimensions: '12 cm de longitud',
        color: 'Rosado grisáceo',
        consistency: 'Blanda',
        margins: 'Proximal (esofágico/gástrico) y Distal (duodenal)',
        orientation: 'Curvatura mayor y menor',
        findings: 'Mucosa con pliegues conservados excepto en región antral.',
        lesions: 'Úlcera de 2.5 cm en curvatura menor, con bordes sobreelevados y fondo necrótico.',
        observations: 'Se disecan 18 ganglios de las estaciones 1 a 7. Se incluyen cortes de lesión, márgenes y ganglios.'
    },
    'Útero (Histerectomía)': {
        sampleType: 'Útero con anexos',
        fragmentCount: '1',
        dimensions: '10 x 7 x 5 cm',
        color: 'Rosado pálido',
        consistency: 'Firme',
        margins: 'Manguito vaginal',
        orientation: 'Anterior/Posterior',
        findings: 'Serosa lisa. Endometrio de 0.4 cm de espesor. Miometrio con múltiples nódulos blanquecinos arremolinados.',
        lesions: 'Leiomiomas intramurales y subserosos, el mayor de 3 cm.',
        observations: 'Se incluyen cortes representativos de cérvix, endometrio, miometrio y leiomiomas.'
    },
    'Colon (Colectomía)': {
        sampleType: 'Segmento de colon',
        fragmentCount: '1',
        dimensions: '15 cm de longitud',
        color: 'Rosado',
        consistency: 'Blanda',
        margins: 'Proximal y Distal',
        orientation: 'Mesocolon',
        findings: 'Mucosa con lesión exofítica de 4 cm que ocupa el 60% de la luz.',
        lesions: 'Tumoración ulcerada, bordes elevados.',
        observations: 'Se identifican 12 ganglios linfáticos en la grasa pericolónica. Se incluyen cortes del tumor, márgenes y ganglios.'
    },
    'Biopsia Endoscópica': {
        sampleType: 'Fragmentos de mucosa gástrica/colónica',
        fragmentCount: 'Múltiples (4)',
        dimensions: '0.2 a 0.3 cm cada uno',
        color: 'Blanquecino-rosado',
        consistency: 'Blanda',
        margins: 'No aplica',
        orientation: 'No orientada',
        findings: 'Pequeños fragmentos irregulares de tejido mucoso.',
        lesions: 'No se identifican lesiones macroscópicas en los fragmentos.',
        observations: 'Se incluyen en su totalidad en 1 cápsula.'
    },
    'Ganglio Linfático': {
        sampleType: 'Ganglio linfático',
        fragmentCount: '1',
        dimensions: '1.5 x 1.0 x 0.8 cm',
        color: 'Pardo grisáceo',
        consistency: 'Firme elástica',
        margins: 'Cápsula ganglionar',
        orientation: 'No orientada',
        findings: 'Superficie externa lisa. Al corte, superficie blanquecina homogénea.',
        lesions: 'No se identifican áreas de necrosis ni hemorragia.',
        observations: 'Se incluye totalmente en 1 cápsula.'
    },
    'Placenta': {
        sampleType: 'Placenta de término',
        fragmentCount: '1',
        dimensions: '18 x 16 x 2.5 cm',
        color: 'Rojizo vinoso',
        consistency: 'Blanda esponjosa',
        margins: 'No aplica',
        orientation: 'Cara fetal / Cara materna',
        findings: 'Cordón umbilical de inserción excéntrica de 30 cm. Membranas completas, translúcidas.',
        lesions: 'Cara materna con cotiledones íntegros. Se identifican pequeñas áreas de infarto blanquecino periférico.',
        observations: 'Se incluyen cortes de cordón, membranas y parénquima placentario (central y periférico).'
    }
};
